corner-radius = 15;
shadow-color = " #000000"
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.2;
shadow-offset-x = -10;
shadow-offset-y = -5;
frame-opacity = 0.9;


rounded-corners-exclude = [
  "class_g = 'Conky'",
  "window_type = 'desktop'"
];

detect-rounded-corners = true;
backend = "glx";
